# arriccio.toml file for Intonaco (Fresco Runtime)

Id = "http://www.hgamer3d.org/component/Intonaco"
Purpose = "Runtime of Fresco Freamework - Intonaco"
Description = """
Intonaco component of the Fresco framework.
The component which glues everything together. 
"""
License = "Apache 2.0 License"

FullLicenseText = """
Copyright 2016 Peter Althainz

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""
signingkey = "https://www.github.com/urs-of-the-backwoods.keys"

#
# Version 2
#

[[Impls]]
  # 64 bit, linux implementation, version 2.0.0
  location = "http://www.hgamer3d.org/downloads/intonaco-amd64-linux-2.0.0.tar.gz"
  signingkey = "https://www.github.com/urs-of-the-backwoods.keys"
  version = "2.0.0"
  architecture = "amd64"
  os = "linux"

[[Impls]]
  # 64 bit, windows implementation, version 2.0.0
  location = "http://www.hgamer3d.org/downloads/intonaco-amd64-windows-2.0.0.tar.gz"
  signingkey = "https://www.github.com/urs-of-the-backwoods.keys"
  version = "2.0.0"
  architecture = "amd64"
  os = "windows"

[[Impls]]
  # 64 bit, mac implementation, version 2.0.0
  location = "http://www.hgamer3d.org/downloads/intonaco-amd64-darwin-2.0.0.tar.gz"
  signingkey = "https://www.github.com/urs-of-the-backwoods.keys"
  version = "2.0.0"
  architecture = "amd64"
  os = "darwin"

#
# Version 1
#

[[Impls]]
  # 64 bit, linux implementation, version 1.0.0
  location = "http://www.hgamer3d.org/downloads/intonaco-amd64-linux-1.0.0.tar.gz"
  signingkey = "https://www.github.com/urs-of-the-backwoods.keys"
  version = "1.0.0"
  architecture = "amd64"
  os = "linux"

[[Impls]]
  # 64 bit, windows implementation, version 1.0.0
  location = "http://www.hgamer3d.org/downloads/intonaco-amd64-windows-1.0.0.tar.gz"
  signingkey = "https://www.github.com/urs-of-the-backwoods.keys"
  version = "1.0.0"
  architecture = "amd64"
  os = "windows"

[[Impls]]
  # 64 bit, mac implementation, version 1.0.0
  location = "http://www.hgamer3d.org/downloads/intonaco-amd64-darwin-1.0.0.tar.gz"
  signingkey = "https://www.github.com/urs-of-the-backwoods.keys"
  version = "1.0.0"
  architecture = "amd64"
  os = "darwin"

#
# Version 0
#

[[Impls]]
  # 64 bit, linux implementation, version 0.1.2
  location = "http://www.hgamer3d.org/downloads/intonaco-amd64-linux-0.1.2.tar.gz"
  signingkey = "https://www.github.com/urs-of-the-backwoods.keys"
  version = "0.1.2"
  architecture = "amd64"
  os = "linux"

[[Impls]]
  # 64 bit, windows implementation
  location = "http://www.hgamer3d.org/downloads/intonaco-amd64-windows-0.1.2.tar.gz"
  signingkey = "https://www.github.com/urs-of-the-backwoods.keys"
  version = "0.1.2"
  architecture = "amd64"
  os = "windows"

[[Impls]]
  # 64 bit, mac implementation
  location = "http://www.hgamer3d.org/downloads/intonaco-amd64-darwin-0.1.2.tar.gz"
  signingkey = "https://www.github.com/urs-of-the-backwoods.keys"
  version = "0.1.2"
  architecture = "amd64"
  os = "darwin"



