sudo: required

services:
  - docker

before_install:
- docker pull debian:wheezy
# - docker run -v $HOME:/fresco debian:wheezy bash -c "/fresco/scripts/prepare-debian.sh && /fresco/scripts/arriccio.sh" 

script:
- ls $HOME
- echo $HOME
