#
#  Fresco Framework for Multi-Language Programming
#  Copyright 2015-2016 Peter Althainz
#    
#  Distributed under the Apache License, Version 2.0
#  (See attached file LICENSE or copy at 
#  http:#www.apache.org/licenses/LICENSE-2.0)
# 
#  file: sinopia/stack.yaml
#

extra-deps: []
resolver: lts-6.27
flags: {}

flags:
  binary-serialise-cbor:
    newtime15: true

packages:
- '.'
- location: '../binary-serialise-cbor'
  extra-dep: true
- location: '../fresco-haskell'
  extra-dep: true

